# Generated by Django 3.2.16 on 2023-01-11 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_length',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(null=True, upload_to='films/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='name_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
