# Generated by Django 3.2.16 on 2023-01-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_film_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='name_original',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
